name = "PrettyTables"
uuid = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
license = "MIT"
desc = "Print data in formatted tables"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.9.0"

[compat]
julia = "1"
Crayons = "4.0"
Formatting = "0.4"
Parameters = "0.12"
Reexport = "0.2"
Tables = "0.2,1.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "Test"]
