name = "PrettyTables"
uuid = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
license = "MIT"
desc = "Print data in formatted tables"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "1.3.1"

[compat]
julia = "1"
Crayons = "4.0"
Formatting = "0.4"
Reexport = "0.2, 1"
Tables = "0.2, 1"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
