name = "PrettyTables"
uuid = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
license = "MIT"
desc = "Print data in formatted tables."
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "2.3.2"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StringManipulation = "892a3eda-7b42-436c-8928-eab12a02cf0e"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Crayons = "4"
LaTeXStrings = "1"
Markdown = "1.6"
OffsetArrays = "1"
PrecompileTools = "1"
Printf = "1.6"
Reexport = "0.2, 1"
StringManipulation = "0.3"
Tables = "0.2, 1"
Test = "1.6"
julia = "1.6"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OffsetArrays", "Test"]
